{
 "title": "Microservices Logs Dashboard",
 "tags": [
  "loki",
  "microservices"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(container_name)" }
  ]
 },
 "panels": [
  {
   "title": "Logs Count (Stat)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({container_name=\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate({container_name=\"$service\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{container_name=\"$service\"} |= \"error\""
    }
   ]
  }
 ]
}