CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS task_db;
CREATE DATABASE IF NOT EXISTS group_task_db;
CREATE DATABASE IF NOT EXISTS progress_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS logging_db;
CREATE DATABASE IF NOT EXISTS class_db;